### ISSUE TITLE
[1-3] Deploy Front-end application as Docker container

### ISSUE THREAD

**Issue by AntonNiko** [SENG499-S22-Company3/shared#5]
See alg 1 github workflow and Github packages for details

**Comment by jayden-chan** [comment]
The frontend is currently deployed to Heroku with docker here: https://seng499company3frontend.herokuapp.com/app/

We're not using GH Actions + container registry for the build, it's just being built on Heroku servers. Is that fine for the frontend since it won't be part of the automated testing? If not I can rebuild our CICD pipeline but I am definitely not going to have time for that until Tuesday at the earliest.

@AntonNiko @aomi
